### ISSUE TITLE
Assignment 1 is ready + a comment

### ISSUE THREAD

**Issue by saraarman** [VIS-2129-F2020/sara_arman-vis#1]
Hi Carole and Aleksander, 

Assignment 1 is ready for submission! Both the Rmd and HTML files are labeled as Assignment_1_VIS. My HTML file is not showing my graphs because it says Github can't show files that large, let me know if you are having trouble seeing them as well. 

Best, 
Sara

**Comment by c-voulgaris** [comment]
Hi Sara, 

I think I can see all the graphs.

You submitted this well before the deadline, so feel free to incorporate the following comments on your code and resubmit before the deadline.

**Detailed code comments:**

Lines 7 and 8: These two lines are probably unnecessary since they repeat what's in your header. Line 8 should probably say "Creative Assignment 1" rather than "Creative Assignment 2", and to get these two lines to show up the way (I think) you intended, you should add a space after the # in line 7.

Line 14: Replace "results='hide'" with "message=FALSE" to keep the html file from displaying all the package loading messages.

Line 27: Add a space after ### to make this a level-three heading

Lines 32 - 37: To get this to show up as a list, add a space after the period that follows each number.

Line 40: You could add " , results='hide'" here to hide the "getting data..." and "using..." messages that show up in your html file.

Line 125: "weight = 5" doesn't do anything. You can delete that. You have a message that R is ignoring it.

Line 127: The reason you have no values on your x-axis is that you've set the tick-mark values (breaks) to be only at 0 and 1, and the minimum value in your dataset is more than 1.

Line 154: Dot plots are tricky! They're cool, but I always struggle to get them to work. These next few comments will help some.

Line 159: It looks like R is just ignoring this line because it's trying to set the color of the inside of your dots with a continuous variable. If you want the whole dot to be one color (the same color for the inside as the the dot outline), change this to "fill = majority_race_eth,"

Line 160: This line doesn't do anything because the size of the dots is determined by the bin width. I suggest deleting it. 

Line 162: The reason your plot looks empty is that your setting the width of each dot to be half of a person (measured along the x axis), which would be too small to see, since your data ranges from 0 to 8000. You'll see dots appear if you set the binwidth to something closer to 100.

Line 175: I suggest a smaller binwidth here (0.07 seems to work well). I would also keep the stackdir as "center" and maybe set alpha=0.5 to make the dots a little bit transparent. That way, with the dots plotted on top of each other, you can see what's behind them.

Lines 191 - 192: Add a space between these two lines so that the heading on line 192 displays the way you want it.

Lines 196 - 203: I suggest looking through the documentation for geom_quantile() to better understand (and describe) what this is doing: https://ggplot2.tidyverse.org/reference/geom_quantile.html

Lines 208 - 216: I think the issue here is that you don't have enough coverage of the full ranges of data for geom_raster() to display anything.  I suggest replacing geom_raster() with geom_point().

Line 212: If you were really doing a raster (which again, I think won't work with this data), size won't mean anything. You'd want to use color instead (i.e. replace this line with "color = avg_hh_sive)) +" If you follow my suggestion and replace geom_raster with geom_point, you can represent avg_hh_size with either size or color. If you use size, I suggest "geom_point(alpha = 0.5)". Setting the alpha value like this will make the points a little bit transparent.

Line 213: Add a "+" at the end of this line.

**Comment by saraarman** [comment]
Hi Carole,

Thank you so much for taking a look at it before the deadline, I really appreciate it. Thanks for the notes, I will work on incorporating this into my code.

See you in class tomorrow!

All my best,
Sara
________________________________

**Comment by saraarman** [comment]
Hi Carole,

I included all of your suggestions in my Rmd and committed it to GitHub, but for some reason, GitHub in my browser is showing my last update as 19 hours ago (when I first submitted). I uploaded my new rmd manually just in case you can only see the old one!

Best,
Sara
________________________________

**Comment by bauranov** [comment]
Carole said it all. Keep up the good work!
